# -*- coding: utf-8 -*-
"""my_pyspark_program1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AN2HDIQwsOOSo3kJKr1QOGcu5zYkoCbe

This is a comment
"""

!wget https://raw.githubusercontent.com/futurexskill/bigdata/master/retailstore.csv

!ls

!wget https://downloads.apache.org/spark/spark-3.1.1/spark-3.1.1-bin-hadoop2.7.tgz

!ls

!tar -xvf spark-3.1.1-bin-hadoop2.7.tgz

!ls

!ls spark-3.1.1-bin-hadoop2.7/

!ls /usr/lib/jvm

import os

os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-11-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.1.1-bin-hadoop2.7"

!ls /content/spark-3.1.1-bin-hadoop2.7

!pip install findspark

import findspark

findspark.init()

from pyspark.sql import SparkSession

spark = SparkSession.builder.master("local[*]").getOrCreate()

!ls

spark.read.option("header",True).csv("retailstore.csv").show()

spark.createDataFrame([{"Google": "Colab","Spark": "Scala"} ,{"Google": "Dataproc","Spark":"Python"}]).show()

